import Head from 'next/head'
import Image from 'next/image'
import {
  Flex,
  Box,
  useColorModeValue,
} from '@chakra-ui/react';
import LoginForm from '../components/LoginForm'

export default function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Box  >
        <Flex
      minH={'100vh'}
      align={'center'}
      justify={'center'}
      bg={useColorModeValue('gray.50', 'gray.800')}>
      <LoginForm redirect />
    </Flex>
        </Box>
    </>
  )
}

