import Head from 'next/head'
import Image from 'next/image'
import {
  Flex,
  Box,
  useColorModeValue,
} from '@chakra-ui/react';
import verifyAuth from '@/services/verifyAuth'
import { setUser } from '@/slices/authSlice'
import { wrapper } from '../store/store'

export default function UserProfile() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Box  >
        <Flex
      minH={'100vh'}
      align={'center'}
      justify={'center'}
      bg={useColorModeValue('gray.50', 'gray.800')}>
     
    </Flex>
        </Box>
    </>
  )
}


export const getServerSideProps = wrapper.getServerSideProps((store) => async ({ req, res }) => {

    const auth = await verifyAuth({ req, store })
    console.log('auth-->',auth)
    if (auth) {
      store.dispatch(setUser(auth))
      return { props: {} }
    } else {
      return {
        props: {},
        redirect: {
          source: '/login',
          destination: '/login',
          permanent: true
        }
      }
    }
  })